### ISSUE TITLE
Evaluator code link is not working.

### ISSUE THREAD

**Issue by shubham8111** [yanaiela/TNE#1]
https://github.com/allenai/tne-evaluator 
This link is not accessible.

**Comment by yanaiela** [comment]
Hi @shubham8111, thanks!
I forgot I need to make it public, and it involves some permission from AI2.
I started the process for making it public, and hope it will be ready in a few days. I'll update when it's done.

Meanwhile, this repo also contain evaluation code, so if you have specific questions let me know.

**Comment by yanaiela** [comment]
https://github.com/allenai/tne-evaluator/
This is now public.
